name: 定时编译并发布SmartDNS

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点执行
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [debian, openwrt, linux, luci]
        arch: [x86-64, arm64, armhf]

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: 安装编译依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev rustc cargo npm

      - name: 编译SmartDNS
        run: |
          package/build-pkg.sh \
            --platform ${{ matrix.platform }} \
            --arch ${{ matrix.arch }} \
            --with-ui \
            --outputdir ./output

      - name: 保存编译产物
        uses: actions/upload-artifact@v3
        with:
          name: smartdns-${{ matrix.platform }}-${{ matrix.arch }}
          path: ./output/*  # 匹配所有类型的产物文件

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: 获取当前日期
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV  # 用命令行生成日期

      - name: 下载所有编译产物
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: 创建GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-build-${{ github.sha }}
          name: 自动构建-${{ env.DATE }}  # 使用环境变量中的日期
          body: 自动定时编译的SmartDNS安装包
          files: ./artifacts/**/*  # 上传所有产物
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
