name: Debian Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  get-version:
    name: Get latest version
    runs-on: ubuntu-latest
    outputs:
      CUR_VERSION: ${{steps.get-version.outputs.CUR_VERSION}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: VERSION_CONTROL
          fetch-depth: 1
          path: version_control
      - name: Extract version
        id: get-version
        run: |
          pre_version=$(cat version_control/VERSION | grep "PREFEX" | sed 's/PREFEX=\(.*\)/\1/')
          cur_version=$(cat version_control/VERSION | grep "CUR_VERS" | sed 's/CUR_VERS=\(.*\)/\1/')
          echo "CUR_VERSION=$pre_version$cur_version" >> $GITHUB_OUTPUT

  build-debian:
    needs: get-version
    strategy:
      matrix:
        arch: [amd64, arm64, armhf]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev
          
      - name: Build SmartDNS Debian package
        run: |
          # 设置版本号
          sed -i "s/VER=.*/VER=${{needs.get-version.outputs.CUR_VERSION}}/" package/build-pkg.sh
          
          # 执行编译
          package/build-pkg.sh \
            --platform debian \
            --arch ${{ matrix.arch }} \
            --with-ui \
            --outputdir ${{ github.workspace }}/build
            
      - name: Rename artifacts
        run: |
          cd ${{ github.workspace }}/build
          for file in smartdns*.deb; do
            newname="${file/-withui/}"
            mv "$file" "$newname"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: deb-packages
          path: ${{ github.workspace }}/build/*.deb

  release:
    needs: [get-version, build-debian]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: deb-packages
          path: ./release-packages

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: deb-${{ needs.get-version.outputs.CUR_VERSION }}
          files: ./release-packages/*.deb
          body: |
            Debian packages for SmartDNS with UI
            * Version: ${{ needs.get-version.outputs.CUR_VERSION }}
            * Supported architectures: amd64, arm64, armhf
