name: Debian Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main  # 使用 main 替代 master

jobs:
  get-version:
    name: Get latest version
    runs-on: ubuntu-latest
    outputs:
      CUR_VERSION: ${{steps.get-version.outputs.CUR_VERSION}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录
      
      - name: Extract version
        id: get-version
        run: |
          # 直接从当前仓库获取版本号
          pre_version=$(grep "PREFEX" VERSION | sed 's/PREFEX=\(.*\)/\1/')
          cur_version=$(grep "CUR_VERS" VERSION | sed 's/CUR_VERS=\(.*\)/\1/')
          echo "CUR_VERSION=$pre_version$cur_version" >> $GITHUB_OUTPUT

  build-debian:
    needs: get-version
    strategy:
      matrix:
        arch: [amd64, arm64, armhf]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev
          
      - name: Build SmartDNS Debian package
        run: |
          # 设置版本号
          sed -i "s/VER=.*/VER=${{needs.get-version.outputs.CUR_VERSION}}/" package/build-pkg.sh
          
          # 执行编译
          mkdir -p build
          package/build-pkg.sh \
            --platform debian \
            --arch ${{ matrix.arch }} \
            --with-ui \
            --outputdir build

      - name: Rename artifacts
        run: |
          cd build
          # 简化文件名
          for file in smartdns*.deb; do
            mv "$file" "${file/-withui/}"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deb-packages
          path: build/*.deb

  release:
    needs: [get-version, build-debian]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: deb-packages
          path: release-packages

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: deb-${{ needs.get-version.outputs.CUR_VERSION }}
          files: release-packages/*.deb
          body: |
            Debian packages for SmartDNS with UI
            * Version: ${{ needs.get-version.outputs.CUR_VERSION }}
            * Supported architectures: amd64, arm64, armhf
